# -*- coding: utf-8 -*-
"""Zomato_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnA4vycv_is7Fajhxs610sMUwkc19adm
"""

print("Hii")

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Zomato data .csv")
df

def handleRate(value):
  value = str(value).split('/')
  value = value[0]
  return float(value)

df['rate'] = df['rate'].apply(handleRate)

df

df.info()

sns.countplot(x = df['listed_in(type)'] , hue=df['listed_in(type)'] , palette = 'Set1' , legend = False)
plt.xlabel('Type of Restaurants')

grouped_data = df.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes' : grouped_data})
result

plt.plot(result , c='green' , marker = 'o')
plt.xlabel("Type of Restaurant", c ='Black', size = 15)
plt.ylabel('Votes' , c = 'Black' , size = 15)

plt.hist(df['rate'] , bins = 12 )
plt.title("Ratings Distribution")
plt.show()

df.head()

couple_Data = df['approx_cost(for two people)']
sns.countplot(x = couple_Data )

plt.figure(figsize = (6,6))
sns.boxplot(x = 'online_order' , y = 'rate' , data = df)

pivot_table = df.pivot_table(index = 'listed_in(type)' , columns = 'online_order' , aggfunc = 'size' , fill_value=0)
sns.heatmap(pivot_table , annot = True , cmap = 'YlGnBu' , fmt = 'd')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed In (type)")
plt.show()

